name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run linters
      run: |
        go version
        go vet ./...
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/kisielk/errcheck@latest
        bash -c "$(go env GOPATH)/bin/staticcheck ./..."
        bash -c "$(go env GOPATH)/bin/errcheck ./..."

    - name: Test
      run: go test ./...
