name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run linters
      run: |
        go version
        go vet ./...
        go install honnef.co/go/tools/cmd/staticcheck@latest
        bash -c "$(go env GOPATH)/bin/staticcheck ./..."

    - name: Test
      run: go test ./...
